#!/bin/bash
#$ -S /bin/sh
#$ -l h_data=20G,h_rt=10:00:00


time1=$( date "+%s" )

echo [Directory] `pwd`
echo [Machine] `uname -n`
echo [Start] `date`
echo [args] $*

export PATH=/share/apps/samtools-1.1/bin:$PATH

vcf_file=$1
outdir=$2
out_name=$3
ref=/coppolalabshares/marisaprj01/Takeda/Pipeline/reference/human_g1k_v37.no_unlocalized_contigs.fasta
input=`cat $vcf_file`

echo "Running:"
echo "gatk overall gvcf"
echo $input

java -Xms2g -Xmx6g -Djava.io.tmpdir=/home/yqin/201505_ExomeSeq/tmp -jar /home/yqin/bin/GenomeAnalysisTK.jar -T CombineGVCFs -o $outdir/$out_name.haplotypecaller.vcf $input -R $ref



time2=$( date "+%s" )
echo [deltat] $(( $time2 - $time1 ))
echo [End] `date`



