#!/bin/bash
#$ -S /bin/sh
#$ -l h_data=4G,h_rt=2:00:00


time1=$( date "+%s" )

echo [Directory] `pwd`
echo [Machine] `uname -n`
echo [Start] `date`
echo [args] $*


output_dir=$1
sg_output_dir=$2
s=$3
sg_s=$4
interval=$5
ref=/coppolalabshares/marisaprj01/Takeda/Pipeline/reference/human_g1k_v37.no_unlocalized_contigs.fasta
vcf=/coppolalabshares/marisaprj01/Takeda/Pipeline/dbSNP/dbsnp_138.b37.vcf

echo "Running:"
echo "gatk haplotype caller"


java -Xmx4g -Xms2g -jar /home/yqin/bin/GenomeAnalysisTK.jar -D $vcf  -L $interval/2014.Takeda.new.intervals -o $sg_output_dir/$sg_s.haplotypecaller.vcf -I $output_dir/$s.aln.dedup.bam -T HaplotypeCaller -R $ref -variant_index_parameter 128000 -variant_index_type LINEAR -nda -maxAltAlleles 4 -ERC GVCF  -contamination 0.02



time2=$( date "+%s" )
echo [deltat] $(( $time2 - $time1 ))
echo [End] `date`
