#!/bin/bash

vcf_list=$1
out_folder=$2
out_name=$3
step=step7_gatk_overall_gvcf
exe=do_step7_gatk_overall_gvcf
F=$4



outdir=$F/$out_folder/Out
logdir=$F/$out_folder/Log
jobdir=$F/$out_folder/Job


mkdir $outdir
mkdir $logdir
mkdir $jobdir

job=$jobdir/$step.$out_name.job


        if [ -e $job ]; then
                echo "$job already exists"

        else
		sleep 2
                qsub -e $logdir -o $logdir -N $step -R y $F/$exe $vcf_list $outdir $out_name > $job
             
                cat $job
        fi



