#!/bin/bash

fastq_digest=$1
step=step1_bwa_aln
exe=do_step1_bwa_aln
F=$2

while read line

do 

	s=`echo $line | awk -F' ' '{print $1}'`
	r1=`echo $line | awk -F' ' '{print $2}'`
	r2=`echo $line | awk -F' ' '{print $3}'`

	
	outdir=$F/results/$s/Out
	logdir=$F/results/$s/Log
	jobdir=$F/results/$s/Job

	job_R1=$jobdir/$step.$s.R1.job
	job_R2=$jobdir/$step.$s.R2.job
	input_R1=$r1
	input_R2=$r2	

	if [ -e $job_R1 ]; then
        	echo "$job_R1 already exists"
	elif [ -e $job_R2 ]; then
		echo "$job_R2 already exists"
	else

        	mkdir -p $logdir
        	mkdir -p $jobdir
        	mkdir -p $outdir
		
		sleep 2
        	qsub -e $logdir -o $logdir -N $step -R y $F/$exe $input_R1 $outdir $s.R1 > $job_R1
		sleep 2
		qsub -e $logdir -o $logdir -N $step -R y $F/$exe $input_R2 $outdir $s.R2 > $job_R2

		cat $job_R1
		cat $job_R2
	fi



done < $fastq_digest

