#!/bin/bash

fastq_digest=$1
step=step6_gatk_ind_gvcf
exe=do_step6_gatk_ind_gvcf
F=$2

while read line

do

        s=`echo $line | awk -F' ' '{print $1}'`

        outdir=$F/results/$s/Out
        logdir=$F/results/$s/Log
        jobdir=$F/results/$s/Job
	
	job=$jobdir/$step.$s.job


        if [ -e $job ]; then
                echo "$job already exists"

        else
		sleep 2
                qsub -e $logdir -o $logdir -N $step -R y $F/$exe $outdir $outdir/sg_haplotypecall_vcf $s > $job
             
                cat $job
        fi



done < $fastq_digest

