#!/bin/bash

echo 'step6 jobs finish '
grep End results/*/Log/step6*.o*|wc




echo 'step6 jobs no errors on files'
grep "Total runtime" results/*/Log/step6*.e*|wc
#grep "Total runtime" results/*/Log/step6*.e*




echo 'step6 jobs killed on files'
grep Killed results/*/Log/step6*.e*|wc
grep Killed results/*/Log/step6*.e*
