#!/bin/bash

echo 'step3 jobs finish '
grep End results/*/Log/step3*.o*|wc




echo 'step3 jobs no errors on files'
grep "UnmappedReadFilter" results/*/Log/step3*.e*|wc
#grep "picard.sam.markduplicates.MarkDuplicates done" results/*/Log/step3*.e*




echo 'step3 jobs killed on files'
grep Killed results/*/Log/step3*.e*|wc
grep Killed results/*/Log/step3*.e*
