#!/bin/bash

echo 'step1 jobs finish '

grep End results/*/Log/step1*.o*|wc

echo 'step1 jobs no errors on files'

grep CPU results/*/Log/step1*.e*|wc

echo 'step1 jobs killed on files'
grep Killed results/*/Log/step1*.e*|wc
grep Killed results/*/Log/step1*.e*
